server:
  port: 80

spring:
  application:
    name: api-gateway-service

  cloud:
    gateway:
      routes:
        - id: service-a
          uri: lb://service-a:8082
          predicates:
            - Path=/api/service-a/**
          filters:
            - name: Hystrix
              args:
                name: service-a
                fallbackuri: forward:/fallback/service-a
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: service-b
          uri: lb://service-b:8083
          predicates:
            - Path=/api/service-b/**
          filters:
            - name: Hystrix
              args:
                name: service-b
                fallbackuri: forward:/fallback/service-b
            - RewritePath=/api/(?<segment>.*), /$\{segment}

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeOutInMilliseconds: 5000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://registry-service:8081/eureka/