server:
  port: 8083

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://registry-service:8081/eureka/

spring:
  zipkin:
    baseUrl: http://zipkin-service:9411/